<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 8" host="NOTEBOOK"><DocLocation><![CDATA[C:\ESD_Test\Bin\ESD_Test]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ESD_Test]]></DName>
<Res><![CDATA[Res121]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:40]]></Time>
<TimeTick>1410122740</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://tfs.innoria.com:3000/]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:40]]></Time>
<TimeTick>1410122740</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" nType="Navigate to http://tfs.innoria.com:3000/" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:40]]></Time>
<TimeTick>1410122740</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[ESD]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:44]]></Time>
<TimeTick>1410122744</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:44]]></Time>
<TimeTick>1410122744</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:44]]></Time>
<TimeTick>1410122744</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:47]]></Time>
<TimeTick>1410122747</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:48]]></Time>
<TimeTick>1410122748</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" >
<Disp><![CDATA[Login_Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:52]]></Time>
<TimeTick>1410122752</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Add Batch Profile]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:52]]></Time>
<TimeTick>1410122752</TimeTick>
<HtmlStep rID="T15">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Bitmap Checkpoint "Add Batch Profile": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 9/8/2014 - 3:45:52</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table></body></html>]]></HTML>
<TimeTick>1410122752</TimeTick>
<NodeArgs eType="Verification" icon="9" nRep="25" status="Passed" >
<Disp><![CDATA[Checkpoint "Add Batch Profile"]]></Disp>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="9" nRep="24" status="Passed" >
<Disp><![CDATA[Add Batch Profile]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Add Batch Profile.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:52]]></Time>
<TimeTick>1410122752</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" >
<Disp><![CDATA[Add Batch Profile.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:52]]></Time>
<TimeTick>1410122752</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:53]]></Time>
<TimeTick>1410122753</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="23" status="Passed" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="14" status="Passed" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<NodeArgs eType="User" icon="10" nRep="35" status="Passed" >
<Disp><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="37" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Press button 'OK' at Browser 'eSkyDesk Management' successfully]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<NodeArgs eType="User" icon="10" nRep="42" status="Passed" >
<Disp><![CDATA[Press button 'OK' at Browser 'eSkyDesk Management' successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AT_Create_BP_Successfull"]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="47" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Create BP Successfull"]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:56]]></Time>
<TimeTick>1410122756</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="45" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:45:59]]></Time>
<TimeTick>1410122759</TimeTick>
<NodeArgs eType="User" icon="10" nRep="51" status="Passed" >
<Disp><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["OK"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="80" status="Warning" >
<Disp><![CDATA["OK"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["OK"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>name=OK<br>micclass=WebButton<br>html tag=BUTTON<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (12 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=OK<SPAN class=Failed> (Skipped)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>html id=ed8a4ce8-690e-4b37-8eef-6388f415778d<SPAN class=Failed> (Skipped)</SPAN><br>value=OK<SPAN class=Failed> (Skipped)</SPAN><br>class=btn btn-default<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="81" >
<Disp><![CDATA["OK"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="82" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="84" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="79" status="Warning" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="78" status="Warning" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Press button 'OK' at Browser 'eSkyDesk Management' successfully]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:03]]></Time>
<TimeTick>1410122763</TimeTick>
<NodeArgs eType="User" icon="10" nRep="85" status="Passed" >
<Disp><![CDATA[Press button 'OK' at Browser 'eSkyDesk Management' successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:23]]></Time>
<TimeTick>1410122783</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:23]]></Time>
<TimeTick>1410122783</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA["OK"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:23]]></Time>
<TimeTick>1410122783</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="246" status="Warning" >
<Disp><![CDATA["OK"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["OK"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>name=OK<br>micclass=WebButton<br>html tag=BUTTON<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (12 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=OK<SPAN class=Failed> (Skipped)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>html id=ed8a4ce8-690e-4b37-8eef-6388f415778d<SPAN class=Failed> (Skipped)</SPAN><br>value=OK<SPAN class=Failed> (Skipped)</SPAN><br>class=btn btn-default<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:23]]></Time>
<TimeTick>1410122783</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="247" >
<Disp><![CDATA["OK"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:23]]></Time>
<TimeTick>1410122783</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="248" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="245" status="Warning" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="244" status="Warning" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:26]]></Time>
<TimeTick>1410122786</TimeTick>
<NodeArgs eType="User" icon="10" nRep="249" status="Passed" >
<Disp><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:29]]></Time>
<TimeTick>1410122789</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:29]]></Time>
<TimeTick>1410122789</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["OK"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:29]]></Time>
<TimeTick>1410122789</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="277" status="Warning" >
<Disp><![CDATA["OK"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["OK"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>name=OK<br>micclass=WebButton<br>html tag=BUTTON<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (12 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=OK<SPAN class=Failed> (Skipped)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>html id=ed8a4ce8-690e-4b37-8eef-6388f415778d<SPAN class=Failed> (Skipped)</SPAN><br>value=OK<SPAN class=Failed> (Skipped)</SPAN><br>class=btn btn-default<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:29]]></Time>
<TimeTick>1410122789</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="278" >
<Disp><![CDATA["OK"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:29]]></Time>
<TimeTick>1410122789</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="279" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:29]]></Time>
<TimeTick>1410122789</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="281" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="276" status="Warning" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="275" status="Warning" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Press button 'OK' at Browser 'eSkyDesk Management' successfully]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:30]]></Time>
<TimeTick>1410122790</TimeTick>
<NodeArgs eType="User" icon="10" nRep="282" status="Passed" >
<Disp><![CDATA[Press button 'OK' at Browser 'eSkyDesk Management' successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:31]]></Time>
<TimeTick>1410122791</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="284" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:31]]></Time>
<TimeTick>1410122791</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:31]]></Time>
<TimeTick>1410122791</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Add Meta Data.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:31]]></Time>
<TimeTick>1410122791</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="288" >
<Disp><![CDATA[Add Meta Data.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="287" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="286" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Get 'Button' with name 'Add Meta Data' at Browser 'eSkyDesk Management' successfully ]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<NodeArgs eType="User" icon="10" nRep="289" status="Passed" >
<Disp><![CDATA[Get 'Button' with name 'Add Meta Data' at Browser 'eSkyDesk Management' successfully ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Add Meta Data.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="293" >
<Disp><![CDATA[Add Meta Data.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Add Meta Data.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="295" >
<Disp><![CDATA[Add Meta Data.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="292" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="291" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Press button 'Add Meta Data' at Browser 'eSkyDesk Management' successfully]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<NodeArgs eType="User" icon="10" nRep="296" status="Passed" >
<Disp><![CDATA[Press button 'Add Meta Data' at Browser 'eSkyDesk Management' successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[WebEdit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:34]]></Time>
<TimeTick>1410122794</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="300" >
<Disp><![CDATA[WebEdit.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="299" >
<Disp><![CDATA[New_BP_Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="298" >
<Disp><![CDATA[eSkyDesk Management]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:37]]></Time>
<TimeTick>1410122797</TimeTick>
<NodeArgs eType="User" icon="10" nRep="301" status="Passed" >
<Disp><![CDATA[Get 'Button' with name 'OK' at Browser 'eSkyDesk Management' successfully ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[eSkyDesk Management]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:37]]></Time>
<TimeTick>1410122797</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[New_BP_Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/8/2014 - 3:46:37]]></Time>
<TimeTick>1410122797</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>